# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Diagonal Device
email: diagonaldevice@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Well, I had to call it something.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ExpHP.github.io"
github_username:  ExpHP
# twitter_username:

# The default for this includes categories, to which I can only say, *whoozasaywatsnow?*
permalink: /:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

comments:
  provider: "staticman"
  staticman:
    allowedFields          : ['name', 'email', 'url', 'message']
    branch                 : "master"
    commitMessage          : "New comment."
    filename               : comment-{@timestamp}
    format                 : "yml"
    moderation             : false
    path                   : "_data/comments/{options.slug}"
    requiredFields         : ['name', 'email', 'message']
    transforms:
      email                : "md5"
    generatedFields:
      date:
        type               : "date"
        options:
          format           : "iso8601"
